---
title: "Playing around with multistate models"
author: "Bradley Saul"
date: `r Sys.Date()`
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(msm)
dt <- readRDS("../data/multistate_basis_pav.rds")
# dt <- readRDS("data/multistate_basis_pav.rds")
```


# Multistate models

TODO: Describe this.

## Assumptions

* no recovery (leaf can't become uninfected by a pathogen)


```{r, echo = TRUE}
states_of_interest <- c("C", "R")

analysis_dt <- dt %>%
  add_interference_indicators(.cutpoint = 0.25) %>%
  add_states(.states = states_of_interest)

states_dt <- analysis_dt %>%
  distinct(!!! rlang::syms(states_of_interest), state, stateL) %>%
  arrange(stateL) 
```


The following are the allowed transitions for each model. Zeros indicate a transition from state $i$ to $j$ is not permitted (except for diagonals -- leaves remain in the same state). The non-zero values don't matter.

```{r, echo = TRUE}
# if infected by C, R, or P can't become uninfected
# if dead can't become undead
Q_start <- find_noreturn_states(1:nrow(states_dt), c("C", "R"), states_dt) %>%
  create_possible_transition_matrix()
Q_start
```

```{r}
simple_msm <- fit_msm(
  formula  = stateL ~ leaf_age,
  subject  = analysis_dt$LeafID,
  data     = analysis_dt,
  startQ   = Q_start,
  covariates = ~ PAV)
```

```{r, echo = FALSE}
grab_data <- function(.msm, .from, .to){
  .msm %>%
    compare_probs(
    t = 0:35, from = .from, to = .to,
    state_labels = states$state,
    .covariates = list(list(PAV = 0),
                       list(PAV = 1)))
}

output <- bind_rows(
  grab_data(simple_msm, 2, 4),
  grab_data(simple_msm, 2, 6),
  grab_data(simple_msm, 3, 4),
  grab_data(simple_msm, 3, 7),
  grab_data(simple_msm, 5, 7),
  grab_data(simple_msm, 5, 6))
```


```{r}
vlines <- data_frame(
  x  = c(0, 0, 0, 1),
  metric = c("p1", "p2", "rd", "rr")
)

output %>% 
  tidyr::gather(key = "metric", value = "value", -comparison, -t, -PAV) %>%
  ggplot(
    data = .,
    aes(x = t, y = value, color = factor(PAV))
  ) + 
  geom_hline(data = vlines, aes(yintercept = x), color = "gray50") + 
  geom_line() + 
  scale_color_manual("PAV", values = c("#fc8d59", "#91bfdb")) + 
  facet_grid(metric ~ comparison, scales = "free_y") +
  theme_classic() +
  theme(
    strip.background = element_blank(),
    axis.line.x      = element_blank(),
    axis.line.y      = element_line(color = "gray50"),
    axis.title.y     = element_blank() 
  )
```

```{r}
pnext0 <- pnext.msm(simple_msm, covariates = list(PAV = 0), ci = "delta")
pnext1 <- pnext.msm(simple_msm, covariates = list(PAV = 1), ci = "delta")

grab_pnext <- function(.msm, .covariates, from, to, state_labels){
    to_label   <- state_labels[to]
    from_label <- state_labels[from]
    msm_pnext  <- pnext.msm(.msm, covariates = .covariates, ci = "delta")
    data.frame(as.list(msm_pnext[from, to]))%>%
      mutate(   
        transition = sprintf("Pr[(%s) --> (%s)]", from_label, to_label),
      ) %>%
      {if(.covariates[1] != "mean") cbind(., as.data.frame(.covariates)) else . }

}

trans <- list(
  c(2, 4), c(2, 6), c(3, 4), c(3, 7), c(5, 7), c(5, 6)
)

pnexts <- bind_rows(
  purrr::map_dfr(trans, .f = ~ grab_pnext(simple_msm, list(PAV = 0), .x[1], .x[2], states$state)),
  purrr::map_dfr(trans, .f = ~ grab_pnext(simple_msm, list(PAV = 1), .x[1], .x[2], states$state))
)
```

```{r}
ggplot(pnexts,
       aes(x = factor(PAV), y = estimate, color = factor(PAV))) + 
  geom_point() + 
  geom_segment(aes(xend = factor(PAV), y = lower, yend = upper)) + 
  scale_color_manual("PAV", values = c("#fc8d59", "#91bfdb")) + 
  facet_grid(~transition)
```

