---
title: "Playing around with multistate models"
author: "Bradley Saul"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(msm)
library(pavPriority)
```


# Multistate models

TODO: Describe this.

## Assumptions

* no recovery (leaf can't become uninfected by a pathogen)

The following are the allowed transitions for each model. Zeros indicate a transition from state $i$ to $j$ is not permitted (except for diagonals -- leaves remain in the same state). The non-zero values don't matter.
```{r poorman_hidden_markov}
times <- pav_dt %>% ungroup() %>%
  distinct(t) %>% arrange(t) %>% pull(t)

dates <- pav_dt %>% ungroup() %>%
  distinct(t, date) %>% arrange(t) %>% pull(date)

leaves_t <- pav_dt %>%
  distinct(LeafID, t)

all_times <- leaves_t %>%
  group_by(LeafID) %>%
  summarise(start = min(t), end = max(t)) %>%
  rowwise() %>%
  mutate(
    x = list(data.frame(t    = times[as.numeric(start) <= times & times <= as.numeric(end)],
                        date = dates[as.numeric(start) <= times & times <= as.numeric(end)]))
  ) %>%
  select(-start, -end) %>%
  tidyr::unnest() %>% 
  ungroup()




temp <- pav_dt %>%
  right_join(all_times, by = c("LeafID", "t", "date")) %>%
  group_by(LeafID) %>%
  arrange(LeafID, t) %>%
  mutate(
    leaf_age =  case_when(
      is.na(ID) ~ lag(leaf_age) + 7,
      TRUE      ~ leaf_age
    ),
    PAV =  case_when(
      is.na(ID) ~ lag(PAV),
      TRUE      ~ PAV
    ),
    C =  case_when(
      is.na(ID) ~ lag(C),
      TRUE      ~ C
    ),
    R =  case_when(
      is.na(ID) ~ lag(R),
      TRUE      ~ R
    ),
    P =  case_when(
      is.na(ID) ~ lag(P),
      TRUE      ~ P
    ),
    D =  case_when(
      is.na(ID) ~ lag(D),
      TRUE      ~ D
    )
  ) %>%
  mutate(
    ID =  case_when(
      is.na(ID) ~ lag(ID),
      TRUE      ~ ID
    )
  )

temp2 <- temp %>%
  arrange(LeafID, leaf_age) %>%
  mutate(
    lC = lag(C, default = 0),
    lR = lag(R, default = 0),
    change = if_else(
      C == 1 & R == 1 & lC == 0 & lR == 0,
      TRUE, FALSE
    ),
    C = ifelse(change, rbinom(1, 1, 0.5), C),
    R = ifelse(change, 1- C, R),
    lC = lag(C, default = 0),
    lR = lag(R, default = 0)
  ) %>%
  select(-change)

lag_tots <- temp2 %>%
  group_by(ID, t) %>%
  summarise(
    sC = sum(C, na.rm = TRUE),
    sR = sum(R, na.rm = TRUE),
    sP = sum(P, na.rm = TRUE),
    n  = n()
  ) %>%
  group_by(ID) %>%
  arrange(ID, t) %>%
  mutate(
    lsC = lag(sC, default = 0),
    lsR = lag(sR, default = 0),
    lsP = lag(sP, default = 0),
    ln  = lag(n, default = 0)
  )
  
temp3 <- temp2 %>%
  left_join(lag_tots, by = c("t", "ID")) %>%
  group_by(LeafID) %>%
  arrange(LeafID, t) %>%
  mutate(
    lpC =  case_when(
      ln == 0       ~ 0,
      leaf_age == min(leaf_age) ~ (lsC)/(ln),
      TRUE          ~ (lsC - lC)/(ln - 1)
    ),
    lpR =  case_when(
      ln == 0       ~ 0,
      leaf_age == min(leaf_age)  ~ (lsR)/(ln),
      TRUE          ~ (lsR - lR)/(ln - 1)
    ),
  )


```

```{r, echo = TRUE}
pC_dt   <- prepare_analysis_data(temp3, c("C", "R", "P")) 
pC_dt$qmatrix[1, 4] <- 0
pC_dt$qmatrix[1, 6] <- 0
pC_dt$qmatrix[1, 7] <- 0
pC_dt$qmatrix[1, 8] <- 0
pC_dt$qmatrix[2, 8] <- 0
pC_dt$qmatrix[3, 8] <- 0
pC_dt$qmatrix[5, 8] <- 0
pC_dt$qdata <- create_q_dataset(pC_dt$qmatrix, pC_dt$states)
# pCpR_dt <- prepare_analysis_data(pav_dt, c("C", "pC", "R", "pR")) 
```

```{r}
pC_dt$data %>%
  group_by(LeafID) %>%
  arrange(LeafID, leaf_age) %>%
  mutate(
    state     = as.character(state),
    lag_state = lag(state, default = ""),
    transition = paste0(lag_state, " -> ", state)
  ) %>%
  select(leaf_age, state, lag_state, transition) %>%
  filter(lag_state != "", state != lag_state) %>%
  group_by(transition) %>%
  summarise(n = n())
```

```{r}
qconstr <- c(1, 2, 3, 4, 5, 6, 7 ,8, 2, 10, 10, 12, -2, 1, 1, 
             16, 5, 18, 5, 8, -2, 22, 22, 12, 25, 26,
             25, 28, 29, 30, -26, 32, 32, 28, -29, 30)
```

```{r, eval = FALSE}
write.csv(cbind(pC_dt$qdata, newq = qconstr), file = "inst/qupdate.csv")
```
A model with no covariates:

```{r, echo = TRUE}
fit <- fit_msm(
  formula     = stateL ~ leaf_age,
  subject     = pC_dt$data$LeafID,
  data        = pC_dt$data,
  startQ      = pC_dt$qmatrix,
  covariates  = ~ lpC + lpR + PAV,
  # qconstraint = qconstr,
  control     = list(fnscale = 6000, maxit = 10000, trace = 1, reltol = 1e-8))
# logLik(fit)
```


```{r, echo = TRUE, eval = FALSE}
fit <- fit_msm(
  formula  = stateL ~ leaf_age,
  subject  = pC_dt$data$LeafID,
  data     = pC_dt$data,
  startQ   = pC_dt$qmatrix,
  qconstraint = qconstr,
  covariates = ~PAV,
  control  = list(fnscale = 15000, trace = 1, maxit = 1000))
```



```{r, echo = FALSE}
grab_transitions <- function(.msm, .from, .to, .covariates){
  .msm %>%
    compare_probs(
      t = 0:35, from = .from, to = .to,
      state_labels = pC_dt$states$state,
      .covariates = .covariates)
}
covs <- list(list(PAV = 0, lpC = 0, lpR = 0),  
             list(PAV = 0, lpC = 1, lpR = 0),
             list(PAV = 0, lpC = 0, lpR = 1),  
             list(PAV = 0, lpC = 1, lpR = 1),
             list(PAV = 1, lpC = 0, lpR = 0),  
             list(PAV = 1, lpC = 1, lpR = 0),
             list(PAV = 1, lpC = 0, lpR = 1),  
             list(PAV = 1, lpC = 1, lpR = 1))
# covs <- NULL
output <- bind_rows(
  grab_transitions(fit, 1, 2, covs),
  grab_transitions(fit, 1, 3, covs),
  grab_transitions(fit, 1, 5, covs),
  grab_transitions(fit, 1, 9, covs),
  grab_transitions(fit, 2, 4, covs),
  grab_transitions(fit, 2, 6, covs),
  grab_transitions(fit, 2, 9, covs),
  grab_transitions(fit, 3, 4, covs),
  grab_transitions(fit, 3, 7, covs),
  grab_transitions(fit, 3, 9, covs),
  grab_transitions(fit, 5, 6, covs),
  grab_transitions(fit, 5, 7, covs),
  grab_transitions(fit, 5, 9, covs),
  grab_transitions(fit, 8, 9, covs))
```


```{r}
vlines <- data_frame(
  x  = c(0, 0, 0, 1),
  metric = c("p1", "p2", "rd", "rr")
)

temp <- output %>% 
  tidyr::gather(key = "metric", value = "value", -comparison, -t, -PAV, -lpC, -lpR) %>%
  mutate(
    lags      = paste("lpC:", lpC, "lpR:", lpR),
    covariate = paste("PAV:", PAV, "lpC:", lpC, "lpR:", lpR)
  )

plot_comparison <- function(dt, title){
  ggplot(
    data = dt %>% filter(t <= 21),
    aes(x = t, y = value, linetype = factor(PAV), color = lags)
  ) + 
  geom_hline(data = vlines, aes(yintercept = x), color = "gray50") + 
  geom_line() + 
  ggtitle(title) +
  scale_color_manual(
    values = c("#e41a1c", "#377eb8", "#4daf4a", "#984ea3")
  ) + 
  facet_grid(metric ~ ., scales = "free_y") +
  theme_classic() +
  theme(
    strip.background = element_blank(),
    axis.line.x      = element_blank(),
    axis.line.y      = element_line(color = "gray50"),
    axis.title.y     = element_blank() 
  )
}

hold <- temp %>%
  group_by(comparison) %>%
  tidyr::nest() %>%
  mutate(
    plot = purrr::map2(data, comparison, plot_comparison),
    fname = stringr::str_replace(comparison, "p1 = ", ""),
    fname = stringr::str_replace(fname, "\\np2 = ", " vs ")
  ) 

for(i in seq_along(hold$fname)){
  ggsave(
    filename = paste0("analysis/figures/", hold$fname[[i]], ".pdf"),
    plot     = hold$plot[[i]],
    height   = 8,
    width    = 4 
  )
}


```



```{r}

tempFUN <- function(t){
  temp <- purrr::map_dfr(
  .x = covs,
  .f = function(x){
    hold <- pmatrix.msm(fit, t = t, covariates = x, ci = "normal")
    df   <- tibble(
            from  = rep(1:9, times = 9),
            to    = rep(1:9, each = 9),
            e     = as.vector(hold$estimates),
            l     = as.vector(hold$L),
            u     = as.vector(hold$U)
          ) %>% cbind(., as.data.frame(x))
  })
    
    
temp2 <- temp %>%
  filter(
    (from == 1 & to == 2) |
    (from == 1 & to == 3) |
    (from == 1 & to == 5) |
    (from == 1 & to == 9) |
    (from == 2 & to == 4) |
    (from == 2 & to == 6) |
    (from == 2 & to == 9) |
    (from == 3 & to == 4) |
    (from == 3 & to == 7) |
    (from == 3 & to == 9) |
    (from == 5 & to == 6) |
    (from == 5 & to == 7) |
    (from == 5 & to == 7) |
    (from == 8 & to == 9) 
  )    %>% 
  mutate(
    from_label = pC_dt$states$state[from],
    to_label   = pC_dt$states$state[to],
    label      = sprintf("Pr(%s|%s)", to_label, from_label),
    lags      = paste("lpC:", lpC, "lpR:", lpR),
    covariate = paste("PAV:", PAV, "lpC:", lpC, "lpR:", lpR)
  )
}

plot_test <- function(dt, title){
  ggplot(
  data = dt,
  aes(y = e, x = covariate, linetype = factor(PAV), color = lags)
) + 
  geom_pointrange(aes(ymin = l, ymax = u)) +
  scale_color_manual(
    values = c("#e41a1c", "#377eb8", "#4daf4a", "#984ea3")
  ) + 
  ggtitle(title) +
  facet_grid(label ~ t, scales = "free_y") +
  # theme_classic() +
  theme(
    axis.text.x = element_blank()
  )

}

bind_rows(
  tempFUN(7)  %>% mutate(t = 7),
  tempFUN(14) %>% mutate(t = 14),
  tempFUN(14) %>% mutate(t = 21)) -> plot_dt

p <- plot_test(plot_dt, "")
ggsave("analysis/figures/p1_with_ci.pdf",
       p, height = 17, width = 11)



```







```{r}
pC_dt$states

```

```{r}
pnext0 <- pnext.msm(simple_msm, covariates = list(PAV = 0), ci = "delta")
pnext1 <- pnext.msm(simple_msm, covariates = list(PAV = 1), ci = "delta")

grab_pnext <- function(.msm, .covariates, from, to, state_labels){
    to_label   <- state_labels[to]
    from_label <- state_labels[from]
    msm_pnext  <- pnext.msm(.msm, covariates = .covariates, ci = "delta")
    data.frame(as.list(msm_pnext[from, to]))%>%
      mutate(   
        transition = sprintf("Pr[(%s) --> (%s)]", from_label, to_label),
      ) %>%
      {if(.covariates[1] != "mean") cbind(., as.data.frame(.covariates)) else . }

}

trans <- list(
  c(2, 4), c(2, 6), c(3, 4), c(3, 7), c(5, 7), c(5, 6)
)

pnexts <- bind_rows(
  purrr::map_dfr(trans, .f = ~ grab_pnext(simple_msm, list(PAV = 0), .x[1], .x[2], states$state)),
  purrr::map_dfr(trans, .f = ~ grab_pnext(simple_msm, list(PAV = 1), .x[1], .x[2], states$state))
)
```

```{r}
ggplot(pnexts,
       aes(x = factor(PAV), y = estimate, color = factor(PAV))) + 
  geom_point() + 
  geom_segment(aes(xend = factor(PAV), y = lower, yend = upper)) + 
  scale_color_manual("PAV", values = c("#fc8d59", "#91bfdb")) + 
  facet_grid(~transition)
```

